name: circyto
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - numpy
  - pandas
  - scipy
  - anndata
  - h5py
  - tqdm
  - typer>=0.9,<1.0
  - rich
