from __future__ import annotations

from pathlib import Path
from typing import List

import pandas as pd


def _parse_splice_sites(path: Path, cell_id: str) -> pd.DataFrame:
    """
    Parse a find_circ3 splice_sites.bed file and add circ_id + cell_id.

    Assumes 18-column legacy format:
      chrom, start, end, name, n_reads, strand,
      bridge_reads, uniq_bridges,
      mapq1, mapq2,
      sample,
      n_uniq_anchors,
      flag1, flag2, flag3, flag4,
      splice_signal,
      tags
    """
    cols = [
        "chrom",
        "start",
        "end",
        "name",
        "n_reads",
        "strand",
        "bridge_reads",
        "uniq_bridges",
        "mapq1",
        "mapq2",
        "sample",
        "n_uniq_anchors",
        "flag1",
        "flag2",
        "flag3",
        "flag4",
        "splice_signal",
        "tags",
    ]
    df = pd.read_csv(
        path,
        sep="\t",
        header=None,
        names=cols,
        dtype={"chrom": str},
    )
    df["cell_id"] = cell_id

    # Standard circ_id format for circyto: chr:start|end|strand
    df["circ_id"] = (
        df["chrom"].astype(str)
        + ":"
        + df["start"].astype(str)
        + "|"
        + df["end"].astype(str)
        + "|"
        + df["strand"].astype(str)
    )
    return df


def _write_matrix_market(df: pd.DataFrame, matrix_path: Path) -> None:
    """
    Write a dense circ x cell integer DataFrame to MatrixMarket (.mtx) in
    coordinate format with 1-based indexing.
    """
    matrix_path = Path(matrix_path)
    n_rows, n_cols = df.shape
    values = df.values

    # Count non-zeros
    nnz = int((values != 0).sum())

    with matrix_path.open("w") as f:
        f.write("%%MatrixMarket matrix coordinate integer general\n")
        f.write("% Generated by circyto.collect_find_circ3\n")
        f.write(f"{n_rows} {n_cols} {nnz}\n")
        for i in range(n_rows):
            for j in range(n_cols):
                val = int(values[i, j])
                if val != 0:
                    # MatrixMarket is 1-based
                    f.write(f"{i+1} {j+1} {val}\n")


def collect_find_circ3_matrix(
    findcirc3_dir: str,
    matrix_path: str,
    circ_index_path: str,
    cell_index_path: str,
    min_count_per_cell: int = 1,
) -> None:
    """
    Collect find_circ3 per-cell *_splice_sites.bed files into a circ x cell
    MatrixMarket matrix + circ/cell index text files.

    Expected layout under findcirc3_dir:
        <findcirc3_dir>/
          <cell_id>/
            <cell_id>_splice_sites.bed
            ...

    Output:
        - matrix_path: MatrixMarket .mtx (rows = circ_id, cols = cell_id)
        - circ_index_path: text file (one circ_id per line)
        - cell_index_path: text file (one cell_id per line)
    """
    root = Path(findcirc3_dir).resolve()
    cell_dirs = [p for p in root.iterdir() if p.is_dir()]

    all_dfs: List[pd.DataFrame] = []

    for cdir in sorted(cell_dirs):
        cell_id = cdir.name
        bed = cdir / f"{cell_id}_splice_sites.bed"
        if not bed.exists():
            print(f"[collect_find_circ3] WARNING: missing {bed}, skipping")
            continue

        df = _parse_splice_sites(bed, cell_id)
        all_dfs.append(df)

    if not all_dfs:
        raise SystemExit("[collect_find_circ3] No splice_sites.bed files found.")

    df_all = pd.concat(all_dfs, ignore_index=True)

    # Build circ x cell counts: sum n_reads per circ_id x cell_id
    counts_df = (
        df_all.groupby(["circ_id", "cell_id"])["n_reads"]
        .sum()
        .reset_index()
        .pivot(index="circ_id", columns="cell_id", values="n_reads")
        .fillna(0)
        .astype(int)
    )

    # Apply per-cell filtering if requested
    if min_count_per_cell > 1:
        col_sums = counts_df.sum(axis=0)
        keep_cols = col_sums[col_sums >= min_count_per_cell].index
        counts_df = counts_df.loc[:, keep_cols]

    # Sort circ_ids and cell_ids for deterministic ordering
    circ_ids = sorted(counts_df.index)
    cell_ids = sorted(counts_df.columns)

    counts_df = counts_df.loc[circ_ids, cell_ids]

    # Write index files
    circ_index_path = Path(circ_index_path)
    cell_index_path = Path(cell_index_path)

    circ_index_path.write_text("\n".join(circ_ids) + "\n")
    cell_index_path.write_text("\n".join(cell_ids) + "\n")

    # Write MatrixMarket
    _write_matrix_market(counts_df, Path(matrix_path))

    print(f"[collect_find_circ3] Wrote matrix: {matrix_path}")
    print(f"[collect_find_circ3] Wrote circ index: {circ_index_path}")
    print(f"[collect_find_circ3] Wrote cell index: {cell_index_path}")
