"""Embedded report styling, kept in Python so wheels need no asset loader."""

STYLE = """
:root{color-scheme:light;--ink:#182b3c;--muted:#516579;--line:#dce4e9;--teal:#157d86}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f3f6f8;color:var(--ink);font:15px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
header{background:#152f40;color:#fff;display:flex;justify-content:space-between;align-items:center;gap:20px;padding:22px max(28px,calc((100% - 1240px)/2));border-bottom:4px solid #27acaa}
.brand{font-size:24px;font-weight:800;letter-spacing:2px;white-space:nowrap}.brand span{font-size:10px;letter-spacing:2px;font-weight:500;margin-left:14px;color:#bbd9de}nav{display:flex;gap:24px}nav a{color:#d9e9f0;text-decoration:none;font-size:13px}
main{max-width:1296px;margin:0 auto;padding:40px 28px}section{margin-bottom:28px;padding:26px 30px;background:#fff;border:1px solid var(--line);border-radius:12px;min-width:0;scroll-margin-top:12px}
#overview{padding:0;background:none;border:0}h1{font-size:36px;line-height:1.2;letter-spacing:-1px;margin:8px 0 10px}h2{font-size:21px;line-height:1.3;margin:0 0 15px}h3{font-size:16px;margin:0}p{margin:10px 0}.eyebrow{font-size:11px;font-weight:800;letter-spacing:2px;color:var(--teal)}.subtitle{color:var(--muted);margin-bottom:22px}.muted{color:var(--muted);font-size:13px}
.status{border:1px solid #e4ca8c;background:#fff8e9;border-left:5px solid #b07919;padding:16px 22px;border-radius:8px}.status h2{font-size:17px;margin-bottom:4px}.status p{margin:0}.status.completed{background:#eef8f4;border-color:#a6d4c1;border-left-color:#238660}.status.failed{background:#fff1ef;border-color:#e7bab2;border-left-color:#ba4940}.status ul{margin:5px 0}
.interpretation{font-size:13px;color:var(--muted);margin:14px 0 22px}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.metric{background:#fff;border:1px solid var(--line);border-radius:9px;padding:20px 22px}.label{text-transform:uppercase;letter-spacing:1px;font-size:10px;font-weight:800;color:var(--muted)}.value{font-weight:750;font-size:34px;line-height:1.3;letter-spacing:-.8px;margin:7px 0;color:#143e50}.metric p{font-size:12px;line-height:1.5;color:var(--muted);margin:0}
.notice{background:#fff7e7;border:1px solid #e8d7af;border-radius:8px;padding:12px 18px;font-size:13px;overflow-wrap:anywhere;margin:0 0 16px}.notice a{color:#745312;font-weight:700}
.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:14px}.section-heading span{color:var(--muted);font-size:12px}.charts{display:grid;grid-template-columns:1fr 1fr;gap:30px}.charts article{min-width:0;padding-top:8px}.charts svg{width:100%;height:auto;display:block}.charts text{font:11px system-ui,sans-serif;fill:#516579}
.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px;text-align:left}th{background:#f3f7f9;font-size:11px;letter-spacing:.3px;color:var(--muted);white-space:nowrap}th,td{padding:11px 13px;border-bottom:1px solid #e4ebef;vertical-align:top}td{overflow-wrap:anywhere}tbody tr:nth-child(even){background:#fbfcfd}code,pre{font:13px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace}pre{background:#152f40;color:#e9f6f6;padding:16px 20px;border-radius:7px;overflow:auto}code{overflow-wrap:anywhere}.warnings{border-left:4px solid #c39b43}.warnings li{margin:6px 0}details{margin:16px 0}summary{cursor:pointer;color:#146b76;font-weight:600;padding:8px 0}footer{text-align:center;padding:12px 24px 40px;color:var(--muted);font-size:12px}a:focus-visible,summary:focus-visible{outline:3px solid #157d86;outline-offset:4px}
@media(max-width:800px){header{display:block;padding:20px}nav{margin-top:12px;gap:18px}.brand span{display:none}main{padding:24px 16px}section{padding:20px 16px}h1{font-size:28px}.metrics{grid-template-columns:1fr 1fr}.charts{grid-template-columns:1fr}.section-heading{display:block}.value{font-size:28px}}
@media(max-width:480px){.metrics{grid-template-columns:1fr}.metric{padding:16px}.value{font-size:30px}}
@media print{body{background:#fff}header{background:#fff;color:#182b3c}nav{display:none}main{padding:12px}section{break-inside:avoid}.table-scroll{overflow:visible}details{display:block}footer{padding:12px}}
"""
